In [1]:
# importing numpy
import numpy as np

In [2]:
# creating a numpy array
a = np.array([5, 6, 9])

In [3]:
# accessing array
a[0]

5

In [4]:
# creating a 2 dimensional array
a = np.array([[1, 2], [3, 4], [5, 6]])

# dimension
print("Dimension is: ", a.ndim)

# shape
print("Shape is", a.shape)

# size of array
print("Number of elements: ", a.size)

# Size of an element
print("Memory one elemnt takes: ", a.itemsize)

#datatype of array
print("Datatype of elements stored: ", a.dtype)

Dimension is:  2
Shape is (3, 2)
Number of elements:  6
Memory one elemnt takes:  4
Datatype of elements stored:  int32


In [5]:
# changing datatype
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.complex)
print("Size increased from 4 to", a.itemsize)
print(a)

Size increased from 4 to 16
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [6]:
# creating an array of zeros
np.zeros(3)

array([0., 0., 0.])

In [7]:
# creating a 2D array of ones
np.ones( (3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# creating an array of 1 to 10(not included) with a step of 2
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [9]:
# creating a linearly spaced array 
#starting(1), ending(5) point and number of elements(10) are known
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [10]:
# changing shape of array
print("Array resahped to\n", a.reshape(2, 3))

# to flat an array wtihout altering original array
print("The flattened array is", a.ravel())

Array resahped to
 [[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
The flattened array is [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


In [11]:
#min
print("Minimum value in the array:", a.min())

#max
print("Maximum value in the array:", a.max())

#sum
print("Sum of all the elements in the array:", a.sum())

#sum of columns
print("Sum of columns:", a.sum(axis=0)) # 0 means top to bottom

#sum of rows
print("Sum of rows:", a.sum(axis=1)) # 1 means left to right

#square root of an array
print("Sqaure roots of the elements:\n", np.sqrt(a))

Minimum value in the array: (1+0j)
Maximum value in the array: (6+0j)
Sum of all the elements in the array: (21+0j)
Sum of columns: [ 9.+0.j 12.+0.j]
Sum of rows: [ 3.+0.j  7.+0.j 11.+0.j]
Sqaure roots of the elements:
 [[1.        +0.j 1.41421356+0.j]
 [1.73205081+0.j 2.        +0.j]
 [2.23606798+0.j 2.44948974+0.j]]


In [12]:
#Dot product of matrices
b=a.reshape(2, 3)
print("Dot product is:", a.dot(b))

Dot product is: [[ 9.+0.j 12.+0.j 15.+0.j]
 [19.+0.j 26.+0.j 33.+0.j]
 [29.+0.j 40.+0.j 51.+0.j]]
