In [1]:
# importing numpy
import numpy as np

In [2]:
#slicing list
a = np.array([6, 7, 8])
print("First two elemnts are:", a[0:2])
print("Last element is:", a[-1])

First two elemnts are: [6 7]
Last element is: 8


In [3]:
#slicing 2D array
a = np.array([[6, 7, 8], [1, 2, 3], [9, 3,2]])
print("Array is\n", a)
print("\nElement in Row 1, column2:", a[1, 2])
print("\nElement in Row 0, column 2 and Row 1, column 2", a[0:2, 2])
print("\nLast row, first two columns elements:", a[-1, 0:2])
print("\nSecond column:\n", a[:, 1:2])
print("\nDisplaying array")
for row in a:
    print(row)
print("\nElements in array")
for cell in a.flat:
    print(cell)

Array is
 [[6 7 8]
 [1 2 3]
 [9 3 2]]

Element in Row 1, column2: 3

Element in Row 0, column 2 and Row 1, column 2 [8 3]

Last row, first two columns elements: [9 3]

Second column:
 [[7]
 [2]
 [3]]

Displaying array
[6 7 8]
[1 2 3]
[9 3 2]

Elements in array
6
7
8
1
2
3
9
3
2


In [4]:
# stacking of array
a = np.arange(6).reshape(3, 2)
b = np.arange(6 ,12).reshape(3, 2)
print("Array a is:\n", a)
print("\nArray b is:\n", b)
print("\nStacking a and b vertically:\n", np.vstack((a, b)))
print("\nStacking a and b horizontally:\n", np.hstack((a, b)))

Array a is:
 [[0 1]
 [2 3]
 [4 5]]

Array b is:
 [[ 6  7]
 [ 8  9]
 [10 11]]

Stacking a and b vertically:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

Stacking a and b horizontally:
 [[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [5]:
# slicing of array
a=np.arange(30).reshape(2, 15)
result=np.hsplit(a, 3)
print("First slice:\n", result[0])
print("Second slice:\n", result[1])
print("Third slice:\n", result[2])

First slice:
 [[ 0  1  2  3  4]
 [15 16 17 18 19]]
Second slice:
 [[ 5  6  7  8  9]
 [20 21 22 23 24]]
Third slice:
 [[10 11 12 13 14]
 [25 26 27 28 29]]


In [6]:
# indexing of boolean array
a = np.arange(12).reshape(3, 4)
print("Array a\n", a)
b=a>4 #checking condition
print("\nThe boolean table for b=a>4:\n", b)
print("\nThe values which gave true: \n", a[b])

Array a
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

The boolean table for b=a>4:
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]

The values which gave true: 
 [ 5  6  7  8  9 10 11]
